# Generated by Django 4.0.4 on 2022-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialtymodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
