# Generated by Django 4.0.4 on 2022-04-21 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_specialtymodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentmodel',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='providermodel',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AlterModelOptions(
            name='specialtymodel',
            options={'verbose_name': 'Specialty', 'verbose_name_plural': 'Specialties'},
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.providermodel', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='providermodel',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialtymodel', verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='specialtymodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
