# Generated by Django 4.0.4 on 2022-04-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointmentmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='approval',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date and Time Approved'),
        ),
    ]
