# Generated by Django 4.0.4 on 2022-04-21 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointmentmodel_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and Time Created'),
            preserve_default=False,
        ),
    ]
