# Generated by Django 4.0.4 on 2022-04-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_providermodel_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='approval',
            new_name='approved',
        ),
    ]
